name: Ubuntu VNC

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git -y

      - name: Configure VNC
        # نستخدم GitHub Secret عشان الأمان
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          # إنشاء مجلد VNC وتعيين الباسورد بشكل غير تفاعلي
          mkdir -p ~/.vnc
          echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          # إنشاء ملف بدء التشغيل
          echo "#!/bin/bash
          xrdb \$HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup

      - name: Start VNC, noVNC, and Tunnel
        run: |
          # تشغيل سيرفر VNC في الخلفية
          vncserver :1 -geometry 1280x720 -depth 24
          
          # تحميل noVNC و websockify
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify
          
          # تشغيل noVNC في الخلفية
          ~/noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 &
          
          # تشغيل النفق كآخر أمر ليبقي الـ job شغالًا
          # سيقوم بطباعة الرابط العام في سجل الأوامر (Logs)
          echo "--> Your VNC is accessible through a browser at the URL provided by serveo.net"
          ssh -o StrictHostKeyChecking=no -R 80:localhost:6080 serveo.net
