name: Ubuntu VNC

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git wget python3 -y

      - name: Configure VNC
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          mkdir -p ~/.vnc
          echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          echo "#!/bin/bash
          xrdb \$HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup

      - name: Start VNC
        run: |
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Start noVNC
        run: |
          git clone --branch v1.2.0 https://github.com/novnc/noVNC.git
          git clone --branch v0.10.0 https://github.com/novnc/websockify noVNC/utils/websockify

          cd noVNC
          chmod +x utils/launch.sh
          nohup ./utils/launch.sh --vnc localhost:5901 --listen 6080 > ../novnc.log 2>&1 &

      - name: Check if noVNC is running
        run: |
          sleep 5
          netstat -tuln | grep 6080 || { echo "noVNC failed to start"; cat novnc.log; exit 1; }

      - name: Start Cloudflared Tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:6080
